apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.client.registry }}:{{ .Values.client.version }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 80Mi
          ports:
            - name: http-web
              containerPort: 80
          env:
            - name: VITE_CLIENT_VERSION
              value: {{ .Values.client.version | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.client.dopplerSecretName }}
      imagePullSecrets:
        - name: {{ .Values.docker.registrySecretName }}
