version: 2.1

jobs:
  publish-helm:
    docker:
      - image: hypnoglow/helm-s3:master-helm3.4
    shell: /bin/sh -leo pipefail
    environment:
      - BASH_ENV: /etc/profile
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            TAG="${CIRCLE_TAG:1}"
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Add Repo
          command: |
            helm repo add demery-s3 s3://helm.demery.net
            helm repo list
      - run:
          name: Package Chart
          command: |
            helm package ./helm --version=$TAG --app-version=$TAG
      - run:
          name: Publish Chart
          command: |
            helm s3 push --relative ./quizlord-client-$TAG.tgz demery-s3

  publish:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=$DOCKER_REGISTRY_URL/$DOCKER_REPOSITORY_CLIENT
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            echo $REGISTRY:$TAG | base64
            docker build -t $REGISTRY:$TAG --build-arg IMAGE_VERSION=$TAG .
      - run:
          name: Push Docker Image
          command: |
            echo $CR_PAT | docker login $DOCKER_REGISTRY_URL -u $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG
  publish-latest:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=$DOCKER_REGISTRY_URL/$DOCKER_REPOSITORY_CLIENT
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG --build-arg IMAGE_VERSION=$TAG .
            docker tag $REGISTRY:$TAG $REGISTRY:latest
      - run:
          name: Push Docker Image
          command: |
            echo $CR_PAT | docker login $DOCKER_REGISTRY_URL -u $DOCKER_USERNAME --password-stdin
            docker push $REGISTRY:$TAG
            docker push $REGISTRY:latest
workflows:
  version: 2
  ci:
    jobs:
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/
          context: quizlord

      - publish-latest:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
          context: quizlord

      - publish-helm:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*.*/
            branches:
              ignore: /.*/
          context: demery-helm-deploy
